'use strict';

module.exports = () => ({
	'jsdoc/check-alignment': 'error',
	'jsdoc/check-examples': 'error',
	'jsdoc/check-indentation': 'error',
	'jsdoc/check-param-names': 'error',
	'jsdoc/check-syntax': 'off',
	'jsdoc/check-tag-names': 'error',
	'jsdoc/check-types': 'error',
	'jsdoc/implements-on-classes': 'error',
	'jsdoc/match-description': 'error',
	'jsdoc/newline-after-description': 'error',
	'jsdoc/no-types': 'error',
	'jsdoc/no-undefined-types': 'error',
	'jsdoc/require-description': 'error',
	'jsdoc/require-description-complete-sentence': 'error',
	'jsdoc/require-example': 'off',
	'jsdoc/require-hyphen-before-param-description': 'error',
	'jsdoc/require-jsdoc': 'error',
	'jsdoc/require-param': 'error',
	'jsdoc/require-param-description': 'error',
	'jsdoc/require-param-name': 'error',
	'jsdoc/require-param-type': 'error',
	'jsdoc/require-returns': 'error',
	'jsdoc/require-returns-check': 'error',
	'jsdoc/require-returns-description': 'error',
	'jsdoc/require-returns-type': 'error',
	'jsdoc/valid-types': 'off',
});
