'use strict';

// https://github.com/yannickcr/eslint-plugin-react

module.exports = () => ({
	'react/boolean-prop-naming': 'error',
	'react/button-has-type': 'error',
	'react/default-props-match-prop-types': 'error',
	'react/destructuring-assignment': 'off',
	'react/display-name': 'error',
	'react/forbid-component-props': 'error',
	'react/forbid-dom-props': 'off',
	'react/forbid-elements': 'off',
	'react/forbid-foreign-prop-types': 'off',
	'react/forbid-prop-types': [
		'error',
		{
			forbid: ['object', 'array'],
		},
	],
	'react/function-component-definition': [
		'error',
		{
			namedComponents: 'function-declaration',
			unnamedComponents: 'arrow-function',
		},
	],
	'react/no-access-state-in-setstate': 'error',
	'react/no-adjacent-inline-elements': 'error',
	'react/no-array-index-key': 'error',
	'react/no-children-prop': 'error',
	'react/no-danger': 'error',
	'react/no-danger-with-children': 'error',
	'react/no-deprecated': 'error',
	'react/no-did-mount-set-state': 'error',
	'react/no-did-update-set-state': 'error',
	'react/no-direct-mutation-state': 'error',
	'react/no-find-dom-node': 'error',
	'react/no-is-mounted': 'error',
	'react/no-multi-comp': 'error',
	'react/no-redundant-should-component-update': 'error',
	'react/no-render-return-value': 'error',
	'react/no-set-state': 'off',
	'react/no-typos': 'error',
	'react/no-string-refs': 'error',
	'react/no-this-in-sfc': 'error',
	'react/no-unescaped-entities': 'error',
	'react/no-unknown-property': 'error',
	'react/no-unsafe': 'error',
	'react/no-unused-prop-types': 'error',
	'react/no-unused-state': 'error',
	'react/no-will-update-set-state': 'error',
	'react/prefer-es6-class': 'error',
	'react/prefer-read-only-props': 'off',
	'react/prefer-stateless-function': [
		'error',
		{
			ignorePureComponents: true,
		},
	],
	'react/prop-types': 'error',
	'react/state-in-constructor': 'error',
	'react/static-property-placement': 'error',
	'react/react-in-jsx-scope': 'error',
	'react/require-default-props': 'error',
	'react/require-optimization': 'error',
	'react/require-render-return': 'error',
	'react/self-closing-comp': 'error',
	'react/sort-comp': 'off',
	'react/sort-prop-types': 'error',
	'react/sort-prop-object': 'off',
	'react/style-prop-object': 'error',
	'react/void-dom-elements-no-children': 'error',

	// JSX-specific rules
	'react/jsx-boolean-value': 'error',
	'react/jsx-child-element-spacing': 'error',
	'react/jsx-closing-bracket-location': 'error',
	'react/jsx-closing-tag-location': 'error',
	'react/jsx-curly-brace-presence': 'error',
	'react/jsx-curly-newline': 'error',
	'react/jsx-curly-spacing': 'error',
	'react/jsx-equals-spacing': 'error',
	'react/jsx-filename-extension': 'off',
	'react/jsx-first-prop-new-line': [
		'error',
		'multiline',
	],
	'react/jsx-handler-names': 'off',
	'react/jsx-indent': [
		'error',
		'tab',
	],
	'react/jsx-indent-props': [
		'error',
		'tab',
	],
	'react/jsx-key': 'error',
	'react/jsx-max-depth': 'off',
	'react/jsx-max-props-per-line': 'off',
	'react/jsx-no-bind': 'error',
	'react/jsx-no-comment-textnodes': 'error',
	'react/jsx-no-duplicate-props': 'error',
	'react/jsx-no-literals': 'off',
	'react/jsx-no-script-url': 'error',
	'react/jsx-no-target-blank': 'error',
	'react/jsx-no-undef': 'error',
	'react/jsx-no-useless-fragment': 'error',
	'react/jsx-one-expression-per-line': 'off',
	'react/jsx-fragments': 'error',
	'react/jsx-pascal-case': 'error',
	'react/jsx-props-no-multi-spaces': 'error',
	'react/jsx-props-no-spreading': 'error',
	'react/jsx-sort-props': 'off',
	'react/jsx-sort-default-props': 'error',
	'react/jsx-tag-spacing': [
		'error',
		{
			closingSlash: 'never',
			beforeSelfClosing: 'always',
			afterOpening: 'never',
		},
	],
	'react/jsx-uses-react': 'error',
	'react/jsx-uses-vars': 'error',
	'react/jsx-wrap-multilines': 'off',
});
