'use strict';

const conditionalRule = require('../../lib/conditional-rule');

module.exports = (configs) => ({
	'@typescript-eslint/adjacent-overload-signatures': 'error',
	'@typescript-eslint/array-type': 'error',
	'@typescript-eslint/await-thenable': 'off',
	'@typescript-eslint/ban-ts-ignore': 'off',
	'@typescript-eslint/ban-types': 'off',
	'@typescript-eslint/camelcase': 'error',
	'@typescript-eslint/class-name-casing': 'error',
	'@typescript-eslint/explicit-function-return-type': conditionalRule(configs, 'error', [
		{configs: ['mocha'], value: 'off'},
	]),
	'@typescript-eslint/explicit-member-accessibility': 'error',
	'@typescript-eslint/func-call-spacing': 'error',
	'@typescript-eslint/generic-type-naming': ['error', '^T[A-Z][a-zA-Z]+$'],
	'@typescript-eslint/indent': ['error', 'tab', {SwitchCase: 1}],
	'@typescript-eslint/interface-name-prefix': 'error',
	'@typescript-eslint/member-delimiter-style': 'error',
	'@typescript-eslint/member-naming': 'error',
	'@typescript-eslint/member-ordering': 'error',
	'@typescript-eslint/no-angle-bracket-type-assertion': 'error',
	'@typescript-eslint/no-array-constructor': 'error',
	'@typescript-eslint/no-empty-interface': 'error',
	'@typescript-eslint/no-explicit-any': 'error',
	'@typescript-eslint/no-extra-parens': [
		'error',
		'all',
		{
			nestedBinaryExpressions: false,
		},
	],
	'@typescript-eslint/no-extraneous-class': ['error', {
		allowConstructorOnly: true,
		allowEmpty: true,
	}],
	'@typescript-eslint/no-for-in-array': 'error',
	'@typescript-eslint/no-inferrable-types': 'error',
	'@typescript-eslint/no-magic-numbers': 'error',
	'@typescript-eslint/no-misused-new': 'error',
	'@typescript-eslint/no-namespace': 'error',
	'@typescript-eslint/no-non-null-assertion': conditionalRule(configs, 'error', [
		{configs: ['mocha'], value: 'off'},
	]),
	'@typescript-eslint/no-object-literal-type-assertion': 'error',
	'@typescript-eslint/no-parameter-properties': 'error',
	'@typescript-eslint/no-require-imports': 'error',
	'@typescript-eslint/no-this-alias': ['error', {
		allowDestructuring: true,
	}],
	'@typescript-eslint/no-triple-slash-reference': 'error',
	'@typescript-eslint/no-type-alias': 'off',
	'@typescript-eslint/no-unnecessary-qualifier': 'error',
	'@typescript-eslint/no-unnecessary-type-assertion': 'error',
	'@typescript-eslint/no-unused-vars': 'error',
	'@typescript-eslint/no-use-before-define': 'error',
	'@typescript-eslint/no-useless-constructor': 'error',
	'@typescript-eslint/no-var-requires': 'error',
	'@typescript-eslint/prefer-for-of': 'error',
	'@typescript-eslint/prefer-function-type': 'error',
	'@typescript-eslint/prefer-includes': 'error',
	'@typescript-eslint/prefer-interface': 'error',
	'@typescript-eslint/prefer-namespace-keyword': 'error',
	'@typescript-eslint/prefer-regexp-exec': 'error',
	'@typescript-eslint/prefer-string-starts-ends-with': 'error',
	'@typescript-eslint/promise-function-async': 'error',
	'@typescript-eslint/require-array-sort-compare': 'off',
	'@typescript-eslint/restrict-plus-operands': 'error',
	'@typescript-eslint/semi': 'error',
	'@typescript-eslint/type-annotation-spacing': 'error',
	'@typescript-eslint/unbound-method': ['error', {
		ignoreStatic: true,
	}],
	'@typescript-eslint/unified-signatures': 'error',
});
