name: Test

on: [push]

jobs:
  shellcheck:
    runs-on: [ubuntu-latest]
    container: 'docker://koalaman/shellcheck-alpine'
    steps:
      - uses: actions/checkout@v2
      - run: './scripts/lint-shell.sh'

  tests:
    name: Node ${{ matrix.node }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run test
      - run: npm run eslint
